language: node_js
node_js:
  - "node"

# exclusions for Bors
branches:
  except:
  - staging.tmp
  - trying.tmp

before_script:
  - npm start -- --silent &

script:
  - npm test
  - $(npm bin)/cypress run
